# Generated by Django 2.2.4 on 2019-08-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BookKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30)),
                ('bcode', models.CharField(max_length=10)),
                ('bprice', models.IntegerField(default=0)),
                ('bedition', models.CharField(max_length=2)),
                ('bstock', models.IntegerField(default=0)),
                ('bauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookKeeper.Author')),
                ('bpublisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookKeeper.Publisher')),
            ],
        ),
    ]
