# Generated by Django 2.2.4 on 2019-08-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookKeeper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookkeeper',
            old_name='loginid',
            new_name='loginname',
        ),
    ]
